# NB: Check loki is ready `curl -s http://localhost:3100/ready`
# `curl -s http://localhost:3100/metrics | grep "loki_"` and find the `loki_` prefixed lines`
# `curl http://localhost:3100/loki/api/v1/labels` find the application label from `pino-loki` config
version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - imagetron-traefik-network
      - loki-network
    volumes:
      - ./loki.config.yaml:/etc/loki/local-config.yaml

networks:

  loki-network:
    name: loki-network
    driver: overlay

  imagetron-traefik-network:
    external: true
