'use strict';

import { inject, injectable } from 'tsyringe';
import { v4 } from 'uuid';
import axios from 'axios';
import path from 'path';

import { CGoAPI, CImages } from '@wherejuly/imagetron-backend-contract';
import { ImagetronException } from '@wherejuly/imagetron-shared';

import { GOAPI_TASK_TYPE_TO_IMAGE_TYPE, IMidjourneyImage, MidjourneyImageEO } from '@src/database/schema/MidjourneyImage.schema.js';
import { GoAPITaskReturnedEventVO } from '@src/ddriven/application/events/GoAPITaskReturnedEvent.valueobject.js';
import S3Adapter from '@src/ddriven/ports/adapters/outgoing/s3/S3.adapter.js';
import { ImageGenerationPromptEO } from '@src/database/schema/ImageGenerationPrompt.schema.js';



/**
 * Service responsible for downloading and persisting images generated by the GoAPI.
 * 
 * This class handles the process of downloading images from provided URLs, generating
 * unique names for them, and uploading them to an S3 storage. It also manages the
 * creation of image objects with metadata and handles errors during the download
 * or upload process.
 * 
 * Dependencies:
 * - S3Adapter: Used for interacting with S3 storage.
 * 
 * Methods:
 * - downloadAndPersist: Downloads images from URLs and persists them.
 * - processImage: Processes a single image, including downloading, naming, and uploading.
 * - makeImage: Creates an image object with metadata.
 * - getImageType: Determines the image type based on task type and input index.
 * - downloadImage: Downloads an image from a URL and returns it as a buffer.
 * - name: Generates a name for the image based on various parameters.
 * - extension: Extracts the file extension from a URL.
 * - slugify: Converts a title into a URL-friendly slug.
 */

@injectable()
export default class ImagesPersistenceService {

    #s3: S3Adapter;

    constructor(@inject(S3Adapter) private readonly s3Adapter: S3Adapter) {
        this.#s3 = s3Adapter;
    }

    public async downloadAndPersist(prompt: ImageGenerationPromptEO, event: GoAPITaskReturnedEventVO): Promise<MidjourneyImageEO[]> {
        // NB: Normalize '/upscale' image URL input into array
        const urls = event.command === CImages.EMidjourneyCommands.Upscale ?
            [event.payload.data.output.image_url] : event.payload.data.output.temporary_image_urls;

        return await Promise.all(urls.map((sourceURL: string, index: number) => {
            return this.processImage(prompt, sourceURL, event, index);
        }));
    }

    // WRITE: TDD for variation name in ImagesPersistenceService tests
    // WRITE: TDD for upscaled name in ImagesPersistenceService tests

    private async processImage(prompt: ImageGenerationPromptEO, sourceURL: string, event: GoAPITaskReturnedEventVO, index: number): Promise<MidjourneyImageEO> {
        const uuid = v4();
        /**
         * INFO: The saved image naming logic is described in the following link.
         * @see https://valentineshi.atlassian.net/browse/IMAGETRON-222
         */
        const name = this.name(prompt, uuid, event.command, sourceURL);

        try {
            // NB: Download image
            const buffer = await this.downloadImage(sourceURL);

            // NB: Upload image tp S3
            const image = this.makeImage(name, sourceURL, uuid, event, index);

            // NB: The pre-signed URL is generated at image creation time To make image cacheable.
            image.url = await this.#s3.preSignedURLFor(image.type, image.name);

            await this.#s3.saveAsImageType(image.type, name, buffer);

            return image;
        } catch (error) {
            const message = error instanceof Error ? error.message : `[${this.constructor.name}] Unexpected error "${String(error)}" .`;

            /**
             * NB: Even the image may be not downloaded or persisted we save the record about it.
             * @see {MidjourneyImageEO} description.
             */
            return this.makeImage(name, sourceURL, uuid, event, index, message);
        }
    }

    /**
     * Creates MidjourneyImageEO entity object.
     */
    private makeImage(name: string, sourceURL: string, uuid: string, event: GoAPITaskReturnedEventVO, index: number, errorMessage?: string): MidjourneyImageEO {
        const pojo: IMidjourneyImage = {
            uuid: uuid,
            // WARNING: Index here is 1-based, not the URLs array 0-based index.
            midjourney_index: index + 1,
            prompt_uuid: event.payload.prompt_uuid,
            task_uuid: event.payload.data.task_id,
            name: name,
            source_url: sourceURL,
            url: null,
            type: this.getImageType(event.payload.data.task_type, event.payload.data.input.index),
            is_persisted: errorMessage ? false : true,
            error_message: errorMessage ?? null,
        };

        return new MidjourneyImageEO(pojo);
    }

    // REFACTOR: Will be clear where this belongs when more places of image object creation reveals.
    /**
     * "Separated" image is the one that comes with GoAPI "upscale" task AND `data.input.index` is 
     * among {@link INDEXES_OF_SEPARATED}.
     * 
     * @see http://localhost:3000/#/schemas/goapi-unified-task-result-data `input.index`
     * 
     * This is rather convoluted due GoAPI does not have the `separate` command. Probably to comply 
     * with Midjourney V5 in the same endpoint.
     * 
     * @param {CGoAPI.EVariationIndex | CGoAPI.EUpscaleIndex} taskInputIndex Not presented in GoAPI
     * `imagine` and `reroll` tasks.
     */
    private getImageType(taskType: CGoAPI.ETaskType, taskInputIndex?: CGoAPI.EVariationIndex | CGoAPI.EUpscaleIndex): CImages.EImageType {
        const INDEXES_OF_SEPARATED = ['1', '2', '3', '4'];

        const isSeparated = taskType === CGoAPI.ETaskType.Upscale && INDEXES_OF_SEPARATED.includes(taskInputIndex!);
        const type = isSeparated ? CImages.EImageType.Separated : GOAPI_TASK_TYPE_TO_IMAGE_TYPE[taskType];

        if (!type) { throw new ImagetronException(`[${this.constructor.name}] Unexpected command "${taskType}" to get image type.`); }

        return type;
    }

    /**
     * Downloads an image from a URL and returns it as a buffer.
     */
    private async downloadImage(url: string): Promise<Buffer> {
        const response = await axios.get(url, { responseType: 'arraybuffer' });
        return Buffer.from(response.data);
    }

    /**
     * The method creates the image names for variation or upscaled image.
     * 
     * WARNING: The `separated` image type so far is named the same way as `variation`
     * but in S3.saveAsImageType it will be saved in the dedicated `separated/` folder.
     * 
     * Examples:
     * - For `upscaled` images name: `a1b2c3d4-a-beautiful-sunset-over-the-mountains.png`. 
     * - For `variation` image: `f9e8d7c6-b5a4-g3h2-j1k0-l9m8n7o6p5q4.png`.
     * 
     * @see https://valentineshi.atlassian.net/browse/IMAGETRON-222
     * @see https://github.com/WhereJuly/63-imagetron/blob/construct/backend/develop/packages/backend/implementation/.a%26cd/model/use-cases/images/save-variations-imagine/save-variations.models.md#images-location-and-naming
     * 
     * @param {ImageGenerationPromptEO} prompt The image generation prompt containing metadata.
     * @param {string} imageUUID The unique identifier for the image.
     * @param {CImages.EMidjourneyCommands} command The command indicating the image processing type.
     * @param {string} sourceURL The URL of the source image.
     * 
     * @returns {string} A string representing the generated filename.
     */
    private name(prompt: ImageGenerationPromptEO, imageUUID: string, command: CImages.EMidjourneyCommands, sourceURL: string): string {
        const extension = this.extension(sourceURL); // NB: Already with leading dot '.'
        const promptHighBits = prompt.uuid?.split('-')[0] ?? 'errored-';

        // NB: The fix for this bug: https://valentineshi.atlassian.net/browse/IMAGETRON-269
        const imageHighBits = imageUUID.split('-')[0] ?? 'errored-';

        const slug = this.slugify(prompt.title);

        /**
         * NB: This also applies to `separated` image type. @see {@link getImageType}
         */
        const isUpscaled = command === CImages.EMidjourneyCommands.Upscale;

        return isUpscaled ? `${promptHighBits}-${slug}-${imageHighBits}${extension}` : `${imageUUID}${extension}`;
    }

    /**
     * Extracts extension with dot from the give URL, e.g. '.jpg
     */
    private extension(url: string): string {
        try {
            const pathname = new URL(url).pathname;
            return path.extname(pathname);
        } catch (_error) {
            return '';
        }
    }

    private slugify(title: string, cutAt: number = 60): string {
        const slug = title.toLowerCase()
            .replace(/[^a-z0-9]+/g, '-'); // Replace multiple non-alphanumeric characters with single hyphens

        return slug.slice(0, cutAt)
            .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens;
    }

}