'use strict';

/**
 * The domain error codes.
 * 
 * @group Convenience
 * @category Exceptions
 */
export enum EDomainErrorCodes {
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
    PROMPT_NOT_FOUND = 'PROMPT_NOT_FOUND',
    ACTIVE_TASK_QUEUE_IS_FULL = 'ACTIVE_TASK_QUEUE_IS_FULL',
    INVALID_PROMPT_STATUS_TRANSITION = 'INVALID_PROMPT_STATUS_TRANSITION',
    MIDJOURNEY_COMMAND_NOT_ALLOWED = 'MIDJOURNEY_COMMAND_NOT_ALLOWED',
    GOAPI_UNEXPECTED_FAILURE = 'GOAPI_UNEXPECTED_FAILURE',
    GOAPI_TASK_FAILURE = 'GOAPI_TASK_FAILURE'
}